### PR TITLE
Map textures

### LINKED ISSUE #263: Texture map
We should add better textures to the current map so it looks better. This will also allow us to publish an initial version of the game before @RoteeSaiMai's friends finalize all the other textures.

### PR DESCRIPTION
**Pull request by vincetiu8**
Fixes #263. Adds textures to every room in the map and adds some objects to give everything life. My drawing is not the best but I think we should stick with the current assets and use this art to release an alpha game. If we really want, we can improve it later.

Also updates doors to have animations when they open.

### CODE REVIEW

**Comment by vincetiu8** [comment]
> Rebuilding barricade causes spam of health indicators, Door hitbox big and can shoot through doors

This PR also addresses these issues.

**Comment by Dyhuan** [comment]
Zombie does no damage.
Objects cannot be moved.

**Comment by Dyhuan** [comment]
Reloading works for everything but the Pistol. Map works fine.

**Review by Dyhuan — APPROVED** [review]
LGTM!

**Pull request merged**
