### PR TITLE
Mega bugfix

### LINKED ISSUE #264: Issues with weapon switching timing
There seems to be an issue with the timing of the weapon cooldown when we're swapping weapons. We should maybe make the current weapon semi-transparent while the cooldown is on just to show the player what weapon they're holding.

### PR DESCRIPTION
**Pull request by vincetiu8**
Fixes #264, #262, #257, #242, #125.

Note that #228 is not technically fully fixed as master client still cannot exit game.

### CODE REVIEW

**Comment by Dyhuan** [comment]
Left debug break in

**Comment by Dyhuan** [comment]
Compile errors when game runs:
error CS0246: The type or namespace name 'Collider2D' could not be found 
error CS0246: The type or namespace name 'Animator' could not be found

**Comment by vincetiu8** [comment]
Should be fixed now.

**Review by CoderAkshat227 — DISMISSED** [review]
A few UI Issues in the main menu, and also the error where it doesn't allow you to leave the game (Photon Error). Other than that, its good.

**Review by BryceLao — CHANGES_REQUESTED** [review]
Spamming start room causes the map to never load
No items can be dropped
Naming a room with an already existing id causes a blank screen
Rebuilding barricade causes spam of health indicators 
-200 health indicator at the start of the game

image
image
image

**Comment by BryceLao** [comment]
Doors when interacted can sometimes pop up the message but not deactivate the weapon or allow to open the door
image

**Comment by BryceLao** [comment]
If a weapon is selected then selected again it will put teh current weapon on cooldown

**Comment by BryceLao** [comment]
Door hitbox big
image

**Comment by BryceLao** [comment]
image

**Comment by BryceLao** [comment]
Barricades sometimes break
image

**Comment by vincetiu8** [comment]
Self-note: pressing options exits the game...

**Comment by BryceLao** [comment]
if person A picks upa box then drops it then person B dies then whebn person B spectates he doenst see what person A is holding also spectator can glitch out and the spectator could see the player in an empty black void
but in reality the person is not

**Comment by Dyhuan** [comment]
back buttons dont work anywhere

**Comment by vincetiu8** [comment]
> A few UI Issues in the main menu, and also the error where it doesn't allow you to leave the game (Photon Error). Other than that, its good.

Fixed

> Spamming start room causes the map to never load, No items can be dropped, -200 health indicator at the start of the game, Naming a room with an already existing id causes a blank screen

Fixed

> Back buttons don't work anywhere

Fixed

> Rebuilding barricade causes spam of health indicators, Door hitbox big and can shoot through doors

Fixed in #266.

> if person A picks upa box then drops it then person B dies then whebn person B spectates he doenst see what person A is holding also spectator can glitch out and the spectator could see the player in an empty black void but in reality the person is not

Can't replicate

**Comment by BryceLao** [comment]
Switching to a weapon and waiting untill it's finished switching then dropping it will immediately allow you to drop teh next weapon and so on. These extra dropped weapons can sometimes appear un switched(transparent). Picking up weapons doesn't reactivate the weapon even when switching to teh slot

**Comment by BryceLao** [comment]
https://youtu.be/W76DuKcaREM

**Comment by vincetiu8** [comment]
> Switching to a weapon and waiting untill it's finished switching then dropping it will immediately allow you to drop teh next weapon and so on. These extra dropped weapons can sometimes appear un switched(transparent). Picking up weapons doesn't reactivate the weapon even when switching to teh slot. It works but it cant be seen

Fixed

> https://youtu.be/W76DuKcaREM

Fixed

**Comment by Dyhuan** [comment]
Sometimes hitting an unopened wall makes you lose -100 health. Not sure if this is intentional.
Gun sometimes doesn't reload even when you still have ammo.
Objects sometimes cannot be put down.
Lots of datatype errors in the scripts: InteractableWindow, BulletController, Menu, NavMeshAssetManager and Explosion.

**Comment by vincetiu8** [comment]
Can't replicate any of the errors.

**Comment by vincetiu8** [comment]
We should probably add ammo counters before releasing the game tho...

**Review by Dyhuan — APPROVED** [review]
LGTM!

**Pull request merged**
